#!/bin/bash

# INSTRUKCJA WDROŻENIA PRZEZ SSH
# Wykonaj te komendy krok po kroku

echo "🚀 WDROŻENIE APLIKACJI - KROK PO KROKU"
echo "======================================"
echo ""
echo "KROK 1: Znajdź dane SSH w panelu Hostinger"
echo "-------------------------------------------"
echo "W panelu Hostinger → SSH access → sprawdź:"
echo "  - Hostname (np. ssh.hostinger.com)"
echo "  - Username (np. u123456789)"
echo "  - Port (domyślnie 22)"
echo ""
echo "KROK 2: Wyślij plik app.py na serwer"
echo "------------------------------------"
echo "Wykonaj tę komendę (UZUPEŁNIJ DANE):"
echo ""
echo "scp -P 22 app.py USERNAME@HOSTNAME:/home/USERNAME/domains/promag.flavorinthejar.com/public_html/"
echo ""
echo "Przykład:"
echo "scp -P 22 app.py u123456789@ssh.hostinger.com:/home/u123456789/domains/promag.flavorinthejar.com/public_html/"
echo ""
echo "KROK 3: Zaloguj się przez SSH"
echo "------------------------------"
echo "ssh -p 22 USERNAME@HOSTNAME"
echo ""
echo "KROK 4: Przejdź do katalogu aplikacji"
echo "--------------------------------------"
echo "cd /home/USERNAME/domains/promag.flavorinthejar.com/public_html"
echo ""
echo "KROK 5: Zrestartuj aplikację"
echo "----------------------------"
echo "pkill -f 'python.*app.py'"
echo "nohup python3 app.py > app.log 2>&1 &"
echo ""
echo "KROK 6: Sprawdź logi"
echo "--------------------"
echo "tail -f app.log"
echo ""
echo "KROK 7: Przetestuj (w nowym terminalu)"
echo "---------------------------------------"
echo "curl https://promag.flavorinthejar.com/api/woocommerce/test"
echo ""
echo "✅ Jeśli zobaczysz JSON z 'status':'ok' - DZIAŁA!"
echo ""
